#!/usr/bin/env python3
"""Exercise installed packages outside Nunchi's checkout, with disposable homes.

Run with the host environment's Python after installing a Nunchi wheel. New
Hermes releases intentionally require a source-installed runtime; --host-mode
records that distinction instead of calling an editable host a wheel proof.
No provider or platform credentials are inherited. Named lanes exercise stock
discovery, normal turns/attention and startup with explicit local doubles, not
authenticated provider or live-room behaviour. Each lane gets a fresh process.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone


def source_identity(root, required_files=('pyproject.toml',)):
    root = Path(root).resolve(strict=True)
    top = subprocess.check_output(["git", "-C", str(root), "rev-parse", "--show-toplevel"], text=True).strip()
    if Path(top).resolve(strict=True) != root:
        raise ValueError('source must be the exact Git root, not an archive inside another repository')
    names = subprocess.check_output(["git", "-C", str(root), "ls-files", "-z"]).split(b"\0")
    if not all(os.fsencode(name) in names for name in required_files) or not any(names):
        raise ValueError('source requires a nonempty tracked project inventory: ' + ', '.join(required_files))
    # Validate all names before reading any bytes (including tracked symlinks).
    for name in filter(None, names):
        path = root / os.fsdecode(name)
        if not path.resolve(strict=True).is_relative_to(root) or not path.is_file():
            raise ValueError('tracked source path escapes project or is not a file')
    commit = subprocess.check_output(["git", "-C", str(root), "rev-parse", "HEAD"], text=True).strip()
    digest = hashlib.sha256()
    for name in sorted(filter(None, names)):
        path = root / os.fsdecode(name)
        digest.update(name + b"\0" + path.read_bytes() + b"\0")
    clean = all(subprocess.run(["git", "-C", str(root), *args], check=False).returncode == 0
                for args in (("diff", "--quiet"), ("diff", "--cached", "--quiet")))
    tree = subprocess.check_output(["git", "-C", str(root), "rev-parse", "HEAD^{tree}"], text=True).strip()
    return {"commit": commit, "tree": tree, "source_sha256": digest.hexdigest(), "tracked_clean": clean}


def distribution_identity(name):
    dist = importlib.metadata.distribution(name)
    digest = hashlib.sha256()
    checked = 0
    for relative in sorted(dist.files or (), key=str):
        # Generated bytecode has no RECORD hash and may be populated on import.
        if relative.hash is None:
            continue
        path = Path(str(dist.locate_file(relative)))
        raw = path.read_bytes()
        import base64
        actual = base64.urlsafe_b64encode(hashlib.new(relative.hash.mode, raw).digest()).decode().rstrip("=")
        assert actual == relative.hash.value, f"RECORD mismatch: {name}/{relative}"
        digest.update(str(relative).encode() + b"\0" + raw + b"\0")
        checked += 1
    direct = json.loads(dist.read_text("direct_url.json") or "{}")
    from urllib.parse import unquote, urlsplit
    location = urlsplit(direct.get("url", ""))
    archive_path = Path(unquote(location.path)) if location.scheme == "file" else None
    archive_sha256 = (hashlib.sha256(archive_path.read_bytes()).hexdigest()
                      if archive_path and archive_path.suffix == ".whl" and archive_path.is_file() else None)
    return {"version": dist.version, "sha256": digest.hexdigest(),
            "record_sha256": hashlib.sha256((dist.read_text("RECORD") or "").encode()).hexdigest(),
            "record_files_checked": checked,
            "direct_url": direct,
            "local_archive_sha256": archive_sha256,
            "artifact_hashes": direct.get("archive_info", {}).get("hashes", {}),
            "editable": direct.get("dir_info", {}).get("editable", False)}


def wheel_identity(wheel, repo):
    import zipfile
    dist = importlib.metadata.distribution("nunchi")
    matched = 0
    with zipfile.ZipFile(wheel) as archive:
        members = {name for name in archive.namelist() if name.startswith("nunchi/") and not name.endswith("/")}
        source_members = {str(path.relative_to(repo / "src")) for path in (repo / "src" / "nunchi").rglob("*")
                          if path.is_file() and "__pycache__" not in path.parts and path.suffix != ".pyc"}
        assert members == source_members, "wheel/source payload file set mismatch"
        for name in archive.namelist():
            if not name.startswith("nunchi/") or name.endswith("/"):
                continue
            raw = archive.read(name)
            assert raw == Path(str(dist.locate_file(name))).read_bytes(), f"installed wheel mismatch: {name}"
            assert raw == (repo / "src" / name).read_bytes(), f"source wheel mismatch: {name}"
            matched += 1
    assert matched > 0, "empty Nunchi wheel"
    return {"filename": wheel.name, "sha256": hashlib.sha256(wheel.read_bytes()).hexdigest(),
            "payload_files_matched": matched}


def child_environment(root, platform, lane):
    home = root / "home"
    home.mkdir()
    hermes_home = home / ".hermes"
    hermes_home.mkdir()
    return {"PATH": os.defpath, "HOME": str(home), "HERMES_HOME": str(hermes_home),
            "PYTHONNOUSERSITE": "1", "PYTHONDONTWRITEBYTECODE": "1",
            "NUNCHI_REQUIRE_HERMES_CONTRACT": "1", "NUNCHI_REQUIRE_HERMES_NORMAL_TURN": "1",
            "NUNCHI_HERMES_PLATFORM": platform,
            "NUNCHI_PROBE_MULTIPLEX": "1" if lane == "startup-multiplex" else "0",
            "TMPDIR": str(root), "LANG": "en_US.UTF-8"}


def main():
    from stock_hermes_probe import LANES
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hermes-source", type=Path, required=True)
    parser.add_argument("--host-mode", choices=("wheel", "source"), required=True)
    parser.add_argument("--platform", choices=("discord", "telegram"), required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--nunchi-wheel", type=Path, required=True)
    parser.add_argument("--host-ref", default="unspecified", help="Requested ref/label; resolved SHA is always recorded")
    parser.add_argument("--lane", choices=LANES, action="append",
                        help="Repeat to select lanes; default: contract only")
    args = parser.parse_args()
    if args.lane and len(set(args.lane)) != len(args.lane):
        parser.error("each lane may only be selected once")
    if args.platform != "discord" and any(lane != "contract" for lane in args.lane or []):
        parser.error("normal/startup lanes exercise Discord; Telegram is contract-only")
    args.hermes_source = args.hermes_source.resolve()

    repo = Path(__file__).resolve().parents[1]
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=False)
    receipt = {"started_at": datetime.now(timezone.utc).isoformat(),
               "platform": args.platform, "host_mode": args.host_mode, "host_ref": args.host_ref,
               "python": sys.version, "executable": sys.executable, "lanes": [],
               "normal_authenticated_turn": "not exercised: loopback model and captured platform doubles",
               "success": False}
    try:
        receipt["source"] = source_identity(repo)
        receipt["dependencies"] = sorted(
            [{"name": dist.metadata["Name"], "version": dist.version} for dist in importlib.metadata.distributions()],
            key=lambda entry: entry["name"].lower())
        receipt["wheel"] = wheel_identity(args.nunchi_wheel.resolve(), repo)
        receipt["before"] = {"host": source_identity(args.hermes_source, ('pyproject.toml', 'hermes_cli/__init__.py', 'gateway/run.py', 'run_agent.py')),
                             "distribution": distribution_identity("hermes-agent"),
                             "nunchi": distribution_identity("nunchi")}
        for lane in args.lane or ["contract"]:
            with tempfile.TemporaryDirectory(prefix="nunchi-stock-") as tmp:
                root = Path(tmp)
                shutil.copytree(repo / "tests", root / "tests", ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
                script = root / "stock_hermes_probe.py"
                shutil.copyfile(repo / "scripts" / script.name, script)
                env = child_environment(root, args.platform, lane)
                result_path = output / f"{lane}.json"
                command = [sys.executable, "-I", "-B", str(script), "--lane", lane,
                           "--hermes-source", str(args.hermes_source), "--host-mode", args.host_mode,
                           "--result", str(result_path)]
                entry = {"lane": lane, "command": command, "started_at": datetime.now(timezone.utc).isoformat()}
                with (output / f"{lane}.log").open("w") as log:
                    try:
                        run = subprocess.run(command, cwd=root, env=env, stdout=log, stderr=subprocess.STDOUT, timeout=500)
                        entry["exit_code"] = run.returncode
                    except subprocess.TimeoutExpired:
                        entry["exit_code"] = 124
                entry["result"] = json.loads(result_path.read_text()) if result_path.exists() else {"success": False}
                entry["finished_at"] = datetime.now(timezone.utc).isoformat()
                receipt["lanes"].append(entry)
                print((output / f"{lane}.log").read_text())
        receipt["after"] = {"host": source_identity(args.hermes_source, ('pyproject.toml', 'hermes_cli/__init__.py', 'gateway/run.py', 'run_agent.py')),
                            "distribution": distribution_identity("hermes-agent"),
                            "nunchi": distribution_identity("nunchi")}
        receipt["integrity_unchanged"] = receipt["before"] == receipt["after"]
        receipt["source_after"] = source_identity(repo)
        receipt["source_unchanged"] = receipt["source"] == receipt["source_after"]
        receipt["success"] = (receipt["integrity_unchanged"] and receipt["before"]["host"]["tracked_clean"]
                              and receipt["source_unchanged"] and receipt["source"]["tracked_clean"]
                              and all(e["exit_code"] == 0 and e["result"]["success"] for e in receipt["lanes"]))
    except Exception:
        import traceback
        receipt["error"] = traceback.format_exc()
    finally:
        receipt["finished_at"] = datetime.now(timezone.utc).isoformat()
        for path in output.glob("*.log"):
            receipt.setdefault("logs", {})[path.name] = {"sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                                                        "text": path.read_text(errors="replace")}
        (output / "receipt.json").write_text(json.dumps(receipt, indent=2) + "\n")
    print(json.dumps(receipt, indent=2))
    return 0 if receipt["success"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
